<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>manejo de errores</title>
</head>
<body>
    <h1>manejo de errores</h1>
    <script>
        // try {
        //     console.log("en el try se agrega el codigo a evaluar");
        //     errorVoluntario
        //     console.log("segunda frase juanda ");
        // } catch (error) {
        //     console.log("catch, captura cualquier error surgido o lanzado en el try");
        //     console.log(error);
        // } finally {
        //     console.log("el bloque finally se ejecutara siempre al final de un bloque try-catch");
        // }




        try {
            let numero = "y";
            if (isNaN(numero)) {
            throw new Error("el caracter introducido no es un numero")    
            }
            console.log(numero * numero);
        } catch (error) {
            console.log(`se produjo el siguiente error: ${error}`);
        }

    </script>
</body>
</html>